# SITE SETTINGS
title: Darwin Core
description: Website for the Darwin Core standard
url: "https://dwc.tdwg.org"

js: >-
  $(document).ready(function() {
      // In quick reference guide: add divider in sidebar after UseWithIRI
      $("a[href='#usewithiri']", "#theme-sidebar-nav").parent().addClass("theme-divider-below");
  });

# BUILD SETTINGS
markdown: kramdown
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
